/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meigSmart_RecoveryMp4_MainActivity */

#ifndef _Included_com_meigSmart_RecoveryMp4_MainActivity
#define _Included_com_meigSmart_RecoveryMp4_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meigSmart_RecoveryMp4_MainActivity
 * Method:    RepairFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_meigSmart_RecoveryMp4_MainActivity_RepairFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
